[package]
name = "drawio-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
quick-xml = "0.38.4"
thiserror = "1"
base64 = "0.22"
flate2 = "1"
percent-encoding = "2"

[dev-dependencies]
serde_json = "1"
walkdir = "2"
similar = "2"
